#!/usr/bin/env python3

import time
import colors as c
print(c.clear)

snake = '''
  .-')        .-') _    ('-.    .-. .-')     ('-.   
 ( OO ).     ( OO ) )  ( OO ).-.\  ( OO )  _(  OO)  
(_)---\_),--./ ,--,'   / . --. /,--. ,--. (,------. 
/    _ | |   \ |  |\   | \-.  \ |  .'   /  |  .---' 
\  :` `. |    \|  | ).-'-'  |  ||      /,  |  |     
 '..`''.)|  .     |/  \| |_.'  ||     ' _)(|  '--.  
.-._)   \|  |\    |    |  .-.  ||  .   \   |  .--'  
\       /|  | \   |    |  | |  ||  |\   \  |  `---. 
 `-----' `--'  `--'    `--' `--'`--' '--'  `------' 
'''


while True:

    for count in range(5):

        for badger in range (12):
            print(c.red + "badgers!")
            time.sleep(0.4)

        for mushroom in range(2):
            print("mushroom")
            time.sleep(0.8)

    print(c.red + snake)
    time.sleep(0.120)


    print(c.clear)
