#!/usr/bin/env python3
import colors as c 
print(c.red + c.clear + '''
who would cross the bridges of death
must answer me these three questions
''') 



print("what is name")
name = input('>')


print("what is quest")
quest = input('>')


if name == 'tristan' or name == 'david':

    print("what is you favorite color")
    color = input('>')
