#!/usr/bin/env python3

import colors as c
import time
dice = []

dice.append('''
 -------
|       |
|   1   |
|       |
 -------
 ''')

dice.append('''
 -------
|       |
|   2   |
|       |
 -------
 ''')

dice.append('''
 -------
|       |
|   3   |
|       |
 -------
 ''')

dice.append('''
 -------
|       |
|   4   |
|       |
-------
''')

dice.append('''
 -------
|       |
|   5   |
|       |
 -------
 ''')

dice.append('''
 -------
|       |
|   6   |
|       |
 -------
 ''')

while True:
    die = random.chocice(dice)
    for die in range(6):
    print(c.clear + c.random_color() + dice[0] + c.reset)
    time.sleep(1)
    input()

