#!/usr/bin/env python3
import colors as c 
from utils import ask
print(c.clear + c.red + """welcome to mad libs""")

text = '''run!
This is how {person} died. {supervillian} plans to relese a {noun2} of fearful
{cutething} {noun1} plan {noun1} to {blank1} you meet up with {person2}.''' 

words = {
    "person" : None,
    "supervillian" :None,
    "noun2" : None,
    "cutething" : None,
    "noun1" : None,
    "blank1": None,
    "person2": None, 
}

for keyword in words:
    words[keyword] = ask(keyword.retrip('0123456789') + ':')

print(c.clear + text.format(**words))
